version: '3.8'

services:
  # React app service (using the pre-built image)
  react-app:
    image: syedowaisnoor/starcom-optimizer-front-end  # Use the pre-built image from Docker Hub
    container_name: react-app
    networks:
      - app-network
    # Since it's a pre-built image, no need for command or volume for src code

  # Nginx service (for serving the app)
  nginx:
    image: nginx:alpine  # Use the official Nginx image for serving
    container_name: nginx
    ports:
      - "8001:80"  # Expose port 80 inside the container on port 8001 externally
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom Nginx config
      - ./dist:/usr/share/nginx/html  # Mount the built React app output into Nginx's html directory
    networks:
      - app-network
    depends_on:
      - react-app  # Ensure that the React app service is up before Nginx starts

# Networks to allow communication between services
networks:
  app-network:
    driver: bridge
