version: '3.8'

services:
  # React app service (using the pre-built image)
  react-app:
    image: syedowaisnoor/starcom-optimizer-front-end  # Use the pre-built image from Docker Hub
    container_name: react-app
    working_dir: /app
    volumes:
      - ./src:/app  # Assuming the source code is in the src directory
    command: ["npm", "run", "build"]  # Run the build process
    networks:
      - app-network
    # No need for a build context, we are using the pre-built image

  # Nginx service (for serving the app)
  nginx:
    image: nginx:alpine  # Use the official Nginx image for serving
    container_name: nginx
    ports:
      - "8001:8001"  # Expose port 8001 for serving the app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom Nginx config
      - ./dist:/usr/share/nginx/html  # Mount the built React app output into Nginx's html directory
    networks:
      - app-network
    depends_on:
      - react-app  # Ensure that the build service (React app) is available before starting Nginx

# Networks to allow communication between services
networks:
  app-network:
    driver: bridge
